### ISSUE TITLE
Buttons 3 and 4 take no action neither on short or on long press

### ISSUE THREAD

**Issue by FachKraft42** [Damian666/HomeAssistant#1]
Hi, I just started to use this blueprint and I have the following problem:

Buttons 1 and 2 are working as expected, but buttons 3 and 4 do nothing with either short or long press. By using traces I figured that the conditions for buttons 3 and 4 don't get triggered and therefore no action is taken. I am available to provide any information necessary to fix this.

**Comment by Raven-Quest** [comment]
should be fixed now?
